name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: Run tests
        run: cargo test -- --nocapture
        env:
          VIAPIKEY: ${{ secrets.VIAPIKEY }}
          VIAPITOKEN: ${{ secrets.VIAPITOKEN }}
